#!/usr/bin/env bash

action=$1
version=$2

SERVICE_INIT_FILE="/etc/init.d/artifactory"
SERVICE_SYSTEMD_FILE="/lib/systemd/system/artifactory.service"
SERVICE_TYPE=""

if [ "$action" = "configure" ]; then
    echo -n "Adding the artifactory service to auto-start..."
    systemctl -h > /dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        #File SERVICE_INIT_FILE exists, backup the file...
        if [ -e ${SERVICE_INIT_FILE} ]; then
            mv ${SERVICE_INIT_FILE} ${SERVICE_INIT_FILE}.disabled
        fi
        systemctl daemon-reload &>/dev/null
        systemctl enable artifactory.service &>/dev/null || $?
        echo -e " DONE"
        SERVICE_TYPE="systemd"
    else
        #File $SERVICE_SYSTEMD_FILE exists, removing...
        if [ -e ${SERVICE_SYSTEMD_FILE} ]; then
            rm -f ${SERVICE_SYSTEMD_FILE}
        fi
        /usr/sbin/update-rc.d artifactory defaults &>/dev/null || $?
        echo -e " DONE"
        SERVICE_TYPE="init.d"
    fi
    echo
    echo -e "\033[33m************ SUCCESS ****************\033[0m"
    echo -e "\033[33mThe Installation of Artifactory has completed successfully.\033[0m"
    echo
    echo "PLEASE NOTE: It is highly recommended to use Artifactory in conjunction with MySQL. You can easily configure this setup using '/opt/jfrog/artifactory/bin/configure.mysql.sh'."
    echo

    if [ ${SERVICE_TYPE} == "init.d" ]; then
        echo "You can now check installation by running:"
        echo "> service artifactory check (or $SERVICE_INIT_FILE check)"
        echo
        echo "Then activate artifactory with:"
        echo "> service artifactory start (or $SERVICE_INIT_FILE start)"
    fi

    if [ ${SERVICE_TYPE} == "systemd" ]; then
        echo "You can activate artifactory with:"
        echo "> systemctl start artifactory.service"
        echo
        echo "Then check the status with:"
        echo "> systemctl status artifactory.service"
    fi

fi

exit 0
